### ISSUE TITLE
share dir not returned when require module is in an eval 

### ISSUE THREAD

**Issue by shawnlaffan** [rschupp/Module-ScanDeps#12]
It seems that, when a module is loaded using require within an eval, any associated share dirs are not listed.  

```bash
scandeps -x -e 'eval qq{require Inline::C}' | grep 'auto/share'

```

When run as a normal require they are found.  

```bash
scandeps.pl -x -e 'require Inline::C' -V | grep 'auto/share'
# auto/share/dist/Inline-C/inline-c.pgx [data]
```

The upshot is that PAR::Packer is missing components when run with code using eval'd requires.

I have not been able to isolate where in Module::ScanDeps this should be corrected.  However these two commands produce the same results so it should not be the data being fed to the scandeps processing code:
```bash
perl -e "eval {require Inline::C}; print join qq{\n}, sort keys %INC"
perl -e "require Inline::C; print join qq{\n}, sort keys %INC"
```

This is more generally a problem for packing Aliens such as Alien::freexl and Alien::spatialite.  These are called from Alien::gdal in this way as they are not essential and so not always installed.

**Comment by rschupp** [comment]
Looks like the `qq{...}` seems to throw `Module::ScanDeps` off:
```
$ scandeps -x -e 'require PAR' | grep PAR
'PAR'                            => '1.018',
'PAR::Heavy'                     => '0.12',
'PAR::SetupProgname'             => '1.002',
'PAR::SetupTemp'                 => '1.002',
$ scandeps -x -e 'eval "require PAR"' | grep PAR
'PAR'                            => '1.018',
'PAR::Heavy'                     => '0.12',
'PAR::SetupProgname'             => '1.002',
'PAR::SetupTemp'                 => '1.002',
$ scandeps -x -e 'eval qq{require PAR}' | grep PAR
'PAR'                           => '1.018',
'PAR::SetupProgname'            => '1.002',
'PAR::SetupTemp'                => '1.002',
```
Huh, where did `PAR::Heavy` go?

**Comment by rschupp** [comment]
Perl's TIMTOWTDI strikes again! Does the following fix the problem?
```
diff --git a/lib/Module/ScanDeps.pm b/lib/Module/ScanDeps.pm
index 5d31eab..e4239c7 100644
--- a/lib/Module/ScanDeps.pm
+++ b/lib/Module/ScanDeps.pm
@@ -983,7 +983,7 @@ sub scan_chunk {
 
         # "eval" with an expression that's a string literal:
         # analyze the string
-        s/^eval \s+ ['"] \s*//x;
+        s/^eval \s+ (?:['"]|qq?.) \s*//x;
 
         # TODO: There's many more of these "loader" type modules on CPAN!
         # scan for the typical module-loader modules
```

**Comment by shawnlaffan** [comment]
Thanks.  Adding that line to scan_chunk seems to correct the issue.  

BTW, is that diff against the repo?  I cannot find the line to modify or the context lines above the change.

**Comment by rschupp** [comment]
@shawnlaffan Forgot to push some commits.Thanks for testing.

**Comment by shawnlaffan** [comment]
Not a problem.  Thanks for fixing.
