### ISSUE TITLE
Cannot find current script 't/date/prefork.pl'

### ISSUE THREAD

**Issue by andk** [rschupp/Module-ScanDeps#16]
Sample fail report: http://www.cpantesters.org/cpan/report/b5f2dabe-0cd0-11ee-bd26-7e119cccb311

Diagnostics there:

``` text
Cannot find current script 't/date/prefork.pl' at /tmp/loop_over_bdir-1501467-RkyV__/Module-ScanDeps-1.31_003-0/blib/lib/Module/ScanDeps.pm line 669.
```

So I went to

https://metacpan.org/release/RSCHUPP/Module-ScanDeps-1.31_003/source/t/13-static_prefork_test.t#L21

The relevant line reads:

``` text
my $root = "t/date/prefork.pl";
```

Did you mean "t/data/prefork.pl" ? The directory `data` exists while the directory `date` doesn't.

**Comment by rschupp** [comment]
> Did you mean "t/data/prefork.pl" ? 
Yeah, thanks!
