### ISSUE TITLE
Moo Roles

### ISSUE THREAD

**Issue by blues1875** [rschupp/Module-ScanDeps#18]
Is it possible to add support for Moo Roles?

**Comment by rschupp** [comment]
@blues1875  What do you mean by that?

**Comment by blues1875** [comment]
If I run scandeps on a script with the following lines:
```
use Moo;
with 'Local::Role::Utils';
```
then I see Moo as a dependency, but not Local::Role::Utils. I'm not sure if that falls under the strict definition of a dependency, but the module is necessary to run the script and it isn't included when running pp.

**Comment by rschupp** [comment]
OK, I see the problem: `Module::ScanDeps` doesn't recognize `with "Foo"` as an importer phrase like `use parent "Foo"`.
Looks doable 😃, maybe `extends Foo`, too (others?).

**Comment by blues1875** [comment]
I haven't come across that, but I think you're absolutely right; it's the same principle. The only other missing dependency I found was XS::Parse::Keyword, which is loaded dynamically by Syntax::Keyword::Try, but I guess that's a harder problem.

**Comment by rschupp** [comment]
`XS::Parse::Keyword` is a nasty one:`'Module::ScanDeps` can't detect it as it's loaded from XS code (by calling `boot_xs_parse_keyword`)! But I can add `%Preload` rules for known users (according to `grep.metacpan.org`):

- Syntax::Keyword::{Combine::Keys,Defer,Dynamically,Inplace,Match,Try}
- Future::AsyncAwait{,::Hooks}
- Object::Pad{,::Keyword::Accessor}
- List::Keywords
- Class::Plain
- XS::Parse::Keyword::FromPerl

**Comment by rschupp** [comment]
@blues1875 Can you try with HEAD? This should recognize `with` and `extends` and adds a  dependency on `XS::Parse::Keyword` for the modules listed above.

**Comment by blues1875** [comment]
Yes, that worked fine... pp_autolink picked up both those dependencies and added them to the exe without having to specify them in the command line. Thanks for the speedy response. I think that will be a useful enhancement. Nice work!

**Comment by rschupp** [comment]
Fixed with f69321da56b58b8f23edaea8c6550c1f40087a28
