### ISSUE TITLE
scan_deps_static needs to pass a %seen in _get_preload() call

### ISSUE THREAD

**Issue by shawnlaffan** [rschupp/Module-ScanDeps#23]
Profiling indicates this line takes a substantial amount of time (>100s) when Moose::Exceptions is scanned.

https://github.com/rschupp/Module-ScanDeps/blob/c9cc39da7ebeab806a28cf052f365ecc2a47214a/lib/Module/ScanDeps.pm#L800

The Moose::Exceptions namespace includes more than 200 modules, each of which depends on Moose.  This results in the Moose sub in %Preload being repeatedly called, each time producing the same result.  

I have not tested yet but it should probably be declared outside the loop starting on L791?
https://github.com/rschupp/Module-ScanDeps/blob/c9cc39da7ebeab806a28cf052f365ecc2a47214a/lib/Module/ScanDeps.pm#L791

**Comment by rschupp** [comment]
> scan_deps_static needs to pass a %seen in _get_preload() call

The `%seen` parameter is there to avoid unnecessary work (or infinite recursion in case of dependency cycles) when expanding preload rules transitively. But we could cache `_get_preload`'s result as you've shown that repeated invocation of preload "sub" and CODE rules adds up substantially. Though in theory, those rules could return different results, e.g. when `@INC` changes during the scan.

**Comment by shawnlaffan** [comment]
Will work up a PR.  

I don't think changes to ```@INC``` are a risk here unless the static scanning checks for such things.  

One option is to use a hash cache with the top level keyed by ```join $Config{path_sep}, @INC, @IncludeLibs```.  Then any changes to the include dirs would automatically start using a different subhash.  The join should be fast enough to regenerate inside each call to ```_get_preload1```.

**Comment by rschupp** [comment]
> I don't think changes to `@INC` are a risk here unless the static scanning checks for such things.

It does recognize stuff like `use lib "/foo/bar"`
https://github.com/rschupp/Module-ScanDeps/blob/cf1e1b31f39e5a0ceb1475ff22317095cc6d01ec/lib/Module/ScanDeps.pm#L962-L976

**Comment by shawnlaffan** [comment]
> It does recognize stuff like ```use lib "/foo/bar"```

This is handled under #24 by using the keys of ```@INC``` as the top level cache key.  Any changes to ```@INC``` will start using a different subhash in the cache.
