### ISSUE TITLE
preload rule for FFI::Platypus missing .pm

### ISSUE THREAD

**Issue by shawnlaffan** [rschupp/Module-ScanDeps#4]
The preload rule for FFI::Platypus lacks the .pm extension.  I assume it should since all the others do, and _get_preload uses an exact match.  

https://github.com/rschupp/Module-ScanDeps/blob/61cc3d73ecf2999f342a195984a67a307e2cba46/lib/Module/ScanDeps.pm#L335

I'm happy to send a PR if that's easier.  

Regards,
Shawn.

**Comment by rschupp** [comment]
Good spotting!

>   I'm happy to send a PR if that's   easier.

Please do.
